#!/bin/sh

case "$1" in
    start)
        echo "Starting fan module..."
        insmod /lib/modules/5.15.148/fan_module.ko
        /root/fand &
        ;;
    stop)
        echo "Stopping fan module..."
        killall /root/fand
        rmmod fan_module
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac